# Generated by Django 6.0.3 on 2026-04-06 13:56

import django.db.models.deletion
import mptt.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Inhalt / Erklärung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.wikinode', verbose_name='Übergeordnetes Kapitel')),
            ],
            options={
                'verbose_name': 'Wiki-Eintrag',
                'verbose_name_plural': 'Wiki-Einträge',
            },
        ),
        migrations.CreateModel(
            name='CommandLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='Terminal Befehl')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Beschreibung')),
                ('is_sudo', models.BooleanField(default=False, verbose_name='Sudo erforderlich')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='wiki.wikinode')),
            ],
            options={
                'verbose_name': 'Befehl',
                'verbose_name_plural': 'Befehle',
            },
        ),
    ]
