# Generated by Django 6.0.3 on 2026-04-11 13:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Std., Pauschale', max_length=50, verbose_name='Einheit')),
                ('net_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Einzelpreis (Netto)')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Standard-MwSt (%)')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TextModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Interner Name, z.B. 'Standard Angebot Intro'", max_length=100, verbose_name='Name')),
                ('module_type', models.CharField(choices=[('INTRO', 'Einleitungstext'), ('OUTRO', 'Schlusstext')], max_length=10, verbose_name='Typ')),
                ('content', models.TextField(help_text='Wird in TinyMCE geladen', verbose_name='Inhalt (HTML)')),
                ('is_default_for_an', models.BooleanField(default=False, verbose_name='Standard für Angebote')),
                ('is_default_for_re', models.BooleanField(default=False, verbose_name='Standard für Rechnungen')),
            ],
            options={
                'verbose_name': 'Textbaustein',
                'verbose_name_plural': 'Textbausteine',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AN', 'Angebot'), ('AB', 'Auftragsbestätigung'), ('LI', 'Lieferschein'), ('RE', 'Rechnung')], default='RE', max_length=2, verbose_name='Dokumententyp')),
                ('document_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Belegnummer')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Gesendet'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='draft', max_length=20, verbose_name='Status')),
                ('seafile_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seafile ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='Belegdatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fälligkeitsdatum')),
                ('intro_text', models.TextField(blank=True, null=True, verbose_name='Einleitungstext')),
                ('outro_text', models.TextField(blank=True, null=True, verbose_name='Schlusstext')),
                ('global_discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Gesamtrabatt (%)')),
                ('skonto_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Skonto (%)')),
                ('skonto_days', models.PositiveIntegerField(default=0, verbose_name='Skonto (Tage)')),
                ('is_small_business', models.BooleanField(default=False, verbose_name='Kleinunternehmerregelung')),
                ('tax_note', models.CharField(blank=True, max_length=255, verbose_name='Steuer-Hinweis')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='erp_documents', to='crm.legalentity', verbose_name='Kunde')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='erp.document')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-document_date', '-document_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('title', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Menge')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='MwSt (%)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Positionsrabatt (%)')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.article')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.document')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positionen',
                'ordering': ['position'],
            },
        ),
    ]
