# Generated by Django 6.0.3 on 2026-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Stück, Stunde, Pauschale', max_length=50, unique=True, verbose_name='Bezeichnung')),
                ('abbreviation', models.CharField(blank=True, help_text='z.B. Stk., Std., mtl.', max_length=10, verbose_name='Abkürzung')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='unit',
        ),
    ]
