# Generated by Django 6.0.3 on 2026-04-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_unit_remove_article_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.unit', verbose_name='Einheit'),
        ),
    ]
