# Generated by Django 6.0.3 on 2026-04-08 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='z.B. Privat oder Geschäftlich', max_length=100)),
                ('auth_type', models.CharField(choices=[('imap_pwd', 'IMAP / SMTP (Passwort)'), ('ms_graph', 'Microsoft 365 / Outlook (OAuth2)'), ('google', 'Google Mail (OAuth2)')], max_length=20)),
                ('encrypted_credentials', models.TextField()),
                ('is_priority', models.BooleanField(default=False, help_text='Wird als Standard-Konto im UI geladen')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail Konto',
                'verbose_name_plural': 'Mail Konten',
            },
        ),
        migrations.CreateModel(
            name='FetchedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id_hash', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_addr', models.CharField(max_length=255)),
                ('to_addr', models.TextField(blank=True)),
                ('cc_addr', models.TextField(blank=True)),
                ('date_sent', models.DateTimeField(db_index=True)),
                ('search_index_text', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_hub.mailaccount')),
            ],
            options={
                'verbose_name': 'Abgerufene E-Mail',
                'verbose_name_plural': 'Abgerufene E-Mails',
                'ordering': ['-date_sent'],
                'unique_together': {('account', 'message_id_hash')},
            },
        ),
        migrations.CreateModel(
            name='MailAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='z.B. FETCH, READ, DELETE, RESTORE', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='mail_hub.fetchedemail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail Revisions-Eintrag',
                'verbose_name_plural': 'Mail Revisions-Einträge',
            },
        ),
    ]
