# Generated by Django 6.0.3 on 2026-04-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='imap_host',
            field=models.CharField(blank=True, help_text='z.B. imap.ionos.de oder imap.gmx.net', max_length=255),
        ),
    ]
