# Generated by Django 6.0.3 on 2026-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_hub', '0002_mailaccount_imap_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='authority',
            field=models.CharField(default='https://login.microsoftonline.com/common', max_length=255),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='client_id',
            field=models.CharField(blank=True, help_text='Azure App Client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='oauth_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='oauth_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='oauth_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
