# Generated by Django 6.0.3 on 2026-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_hub', '0003_mailaccount_authority_mailaccount_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailaccount',
            name='encrypted_credentials',
            field=models.TextField(blank=True, null=True, verbose_name='Verschlüsselte Zugangsdaten (nur für IMAP)'),
        ),
    ]
