# Generated by Django 6.0.3 on 2026-04-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_hub', '0004_alter_mailaccount_encrypted_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedemail',
            name='folder_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fetchedemail',
            name='remote_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
