# Generated by Django 6.0.3 on 2026-04-08 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_hub', '0005_fetchedemail_folder_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailauditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Mail Revisions-Eintrag', 'verbose_name_plural': 'Mail Revisions-Einträge'},
        ),
        migrations.CreateModel(
            name='MailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=100)),
                ('content_html', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='mail_hub.mailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_mode', models.CharField(choices=[('vertical', 'Vorschau rechts'), ('horizontal', 'Vorschau unten'), ('none', 'Keine Vorschau')], default='vertical', max_length=20)),
                ('show_unified_inbox', models.BooleanField(default=True)),
                ('favorites', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFolderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_hub.mailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('user', 'account', 'folder_path')},
            },
        ),
    ]
