# Generated by Django 6.0.3 on 2026-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_hub', '0006_alter_mailauditlog_options_mailsignature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='z.B. smtp.ionos.de', max_length=255),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
    ]
