# Generated by Django 6.0.3 on 2026-03-19 10:19

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Titelbild')),
                ('part_title', models.CharField(max_length=200, verbose_name='Teil (z.B. Teil 2: Die Akutphase)')),
                ('chapter_title', models.CharField(max_length=200, verbose_name='Kapitel (z.B. Kapitel 3: Der Tag X)')),
                ('chapter_subtitle', models.CharField(blank=True, max_length=200, verbose_name='Untertitel')),
                ('introduction', tinymce.models.HTMLField(verbose_name='Kapitel Einleitung')),
                ('content', tinymce.models.HTMLField(verbose_name='Hauptinhalt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='PostDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_label', models.CharField(help_text='z.B. Checkliste Notfallplan', max_length=100)),
                ('file', models.FileField(upload_to='downloads/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='blog.blogpost')),
            ],
        ),
    ]
