# Generated by Django 6.0.3 on 2026-04-07 07:56

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('HERR', 'Mr.'), ('FRAU', 'Ms.'), ('DIVERS', 'Diverse'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10, verbose_name='Salutation')),
                ('title', models.CharField(blank=True, help_text='e.g. Dr., Prof. Dr.', max_length=100, verbose_name='Title')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('pref_lang', models.CharField(choices=[('DE', 'German'), ('ES', 'Spanish'), ('EN', 'English')], default='DE', max_length=2, verbose_name='Preferred Language')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('COMPANY', 'Company / Organization'), ('PRIVATE', 'Private Person')], default='COMPANY', max_length=10, verbose_name='Entity Type')),
                ('internal_id', models.CharField(default=crm.models.generate_customer_number, max_length=50, unique=True, verbose_name='Customer Number')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='VAT/NIF/CIF ID')),
                ('tax_id_local', models.CharField(blank=True, max_length=50, verbose_name='Local Tax ID')),
                ('tax_regime', models.CharField(choices=[('REGULAR', 'Regular (VAT/IVA)'), ('IGIC', 'Tenerife/Canaries (IGIC)'), ('REVERSE', 'Reverse Charge / Export')], default='REGULAR', max_length=10, verbose_name='Tax Regime')),
                ('is_zec_approved', models.BooleanField(default=False, verbose_name='ZEC Approved')),
                ('webseite', models.URLField(blank=True, verbose_name='Website')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='crm.legalentity', verbose_name='Parent Company')),
                ('is_private_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_legal_entity', to='crm.person')),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CALL', 'Phone Call'), ('MEETING', 'Meeting'), ('NOTE', 'Note'), ('EMAIL', 'E-Mail')], default='NOTE', max_length=10, verbose_name='Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='crm/interactions/', verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.legalentity')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.person')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('INTERNAL', 'Internal / Permanent'), ('FREELANCE', 'Freelancer'), ('SUB', 'Sub-Contractor')], default='INTERNAL', max_length=10, verbose_name='Employment Type')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Department')),
                ('is_allgemein', models.BooleanField(default=True, verbose_name='General Contact')),
                ('is_re_contact', models.BooleanField(default=False, verbose_name='Invoice Recipient')),
                ('is_ls_contact', models.BooleanField(default=False, verbose_name='Shipping Contact')),
                ('is_as_contact', models.BooleanField(default=False, verbose_name='Order Contact')),
                ('is_vertrag', models.BooleanField(default=False, verbose_name='Contract Contact')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.legalentity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.person')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
            },
        ),
        migrations.CreateModel(
            name='CommChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('MAIL', 'E-Mail'), ('PHONE', 'Phone'), ('MOBILE', 'Mobile'), ('WHATSAPP', 'WhatsApp'), ('SIGNAL', 'Signal'), ('FAX', 'Fax')], max_length=10, verbose_name='Type')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(blank=True, help_text='e.g. Office, Private', max_length=100, verbose_name='Label')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='crm.legalentity')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('BILLING', 'Billing Address'), ('SHIPPING', 'Shipping Address'), ('PRIVATE', 'Private Address'), ('BRANCH', 'Branch Office')], default='BILLING', max_length=10, verbose_name='Address Type')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('street_extra', models.CharField(blank=True, help_text='Apt, Building, Local', max_length=255, verbose_name='Street Extra')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP Code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=255, verbose_name='Province/State')),
                ('country', models.CharField(default='Germany', max_length=100, verbose_name='Country')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.legalentity')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
